### ISSUE TITLE
Add Splunk License

### ISSUE THREAD

**Issue by tonyprinzler** [thesplunker/Splunkenizer#15]
**Describe the bug**
After the license file is copied to the /tmp folder of the license master, splunk is not able to read/add the file.
The file has only read/write permissions for root. 

**Execution in:**
ansible/roles/license_master/tasks/add_license.yml

**Changes to fix:**
set ownership in the copy task fixed the problem:
  owner: "{{ splunk_user }}"

**Desktop (please complete the following information):**
 - OS:  CentOS 8
 - Ansible Version: ansible 2.9.15

**Comment by splunkenizer** [comment]
I never had an issue so far, but I agree this should be copied with the correct owner. This is fixed now.
