### ISSUE TITLE
Software folder

### ISSUE THREAD

**Issue by olivierpas** [thesplunker/Splunkenizer#17]
Hello,

Does Vagrant is mandatory ?
Can i place the Software folder somewhere else ? i mean under /Splunkenizer/Software or on a web server.
The project is amazing but i have a misunderstand with files location ( .lic files / splunk.tgz ... )

Regards,
Olivier

**Comment by olivierpas** [comment]
My bad i find : Splunkenizer/defaults/splunk_dirs.yml

**Comment by splunkenizer** [comment]
Hi Oliver

Vagrant is not mandatory. You can use the ansible part without vagrant. But
you have to create your virtual servers yourself or have just physical
servers available.
https://github.com/splunkenizer/Splunkenizer#ansible-playbooks-only

As you already found out you can change the folders for lics, software,
etc. . Please do not change files in the defaults directory. You can
overwrite the default settings in splunk_config.yml. All the settings are
explained in this file:
https://github.com/splunkenizer/Splunkenizer/blob/master/examples/configuration_description.yml

Hope that helps

Regards,


*Marco Stadler*
