### ISSUE TITLE
pip3 ansible package needed when running on ubuntu 20.04

### ISSUE THREAD

**Issue by MattUebel** [thesplunker/Splunkenizer#26]
Opening this one for visibility, and perhaps an update to the docs

Received this error running deploy_site.yml:

```
Malformed output discovered from systemd list-unit-files
```

Saw similar message at https://github.com/DataDog/ansible-datadog/issues/274

This seems to occur on Ubuntu 20.04 (at least), and is related to the default ansible package for the distribution being out of date.

I was able to resolve it by installing the pip3 version of ansible, which is `2.12.4` currently.

**Comment by splunkenizer** [comment]
In general the playbooks should work with ansible 2.7+ but that seems not to be the case for Ubuntu. Unfortunately, lots of linux distros ship with way outdated ansible and python versions. I might need to check the ansible version in the code. I have added this to the known issues section in the readme.
