### ISSUE TITLE
defaults for idxc_sf and idxc_rf

### ISSUE THREAD

**Issue by MattUebel** [thesplunker/Splunkenizer#27]
I used the configuration reference, but didn't catch in the examples where the rep and search factors need to be specified.

This might be something worth setting a default for.

**Comment by splunkenizer** [comment]
Good catch. There is an example config for a non multi-site cluster at [examples/cm_2idxc_sh_uf.yml](https://github.com/splunkenizer/Splunkenizer/blob/master/examples/cm_2idxc_sh_uf.yml). But I have updated this in the configuration reference also.
