### ISSUE TITLE
lxml module needed for license manager role

### ISSUE THREAD

**Issue by MattUebel** [thesplunker/Splunkenizer#28]
**Describe the bug**
Playbook failed at the license manager role. 

```
ModuleNotFoundError: No module named 'lxml'
```

**Desktop (please complete the following information):**
ubuntu 20.04.1
ansible 2.14.4
python 3.8.10

**Additional context**
This may be related to my specific distro

I was able to get around it by installing `lxml`, but didn't find this mentioned in the docs, so might be a good update.

**Comment by splunkenizer** [comment]
I have updated the docs to include that. See the installation section. I might add a check in the code to make sure this lib is available before running the playbooks.
