### ISSUE TITLE
master to manager terminology change breaks the playbooks

### ISSUE THREAD

**Issue by MattUebel** [thesplunker/Splunkenizer#29]
**Describe the bug**
The base configs from splunk have changed the terminology from `master` to `manager`. This breaks the playbooks.

**Additional context**
This happened once I got to the cluster manager role. The copy files task failed to find the cluster master related configs because they have been renamed to cluster manager.

I was able to get a successful playbook execution by renaming the directories.

**Comment by splunkenizer** [comment]
I did have this on the radar and todo list to implement. I did not expect the base_configs to be updated so soon. I will have to update this in the code. The only workaround I currently see is to rename the relevant settings in the base_configs to the old naming until I have updated the code.

**Comment by MattUebel** [comment]
another note on this, renaming folders was an effective workaround to get the playbook to complete, but the resulting indexers were broken as 

```
manager_uri = <CLUSTER_MANAGER_MGMT_PORT_URI>
```

ended up being left in the indexer base app

**Comment by MattUebel** [comment]
likewise for `cluster_search_base`

**Comment by splunkenizer** [comment]
Has been fixed fix introducing Splunk 9.x support
