### ISSUE TITLE
Splunk manager versus master change in Automator

### ISSUE THREAD

**Issue by guilhemmarchand** [thesplunker/Splunkenizer#38]
**Describe the bug**

- The Automator keeps geenrating applications in the $SPLUNK_HOME/etc/master-apps rather than $SPLUNK_HOME/etc/manager-apps, which is now the right practice in Splunk 9.x.

**Comment by splunkenizer** [comment]
This issue has been fixed with Pull Request  https://github.com/splunk/splunk-platform-automator/pull/39
