### ISSUE TITLE
cleaning or correcting ansible connection info when vagrant reload or vagrant provision is run

### ISSUE THREAD

**Issue by kundeng** [thesplunker/Splunkenizer#8]
**Describe the bug**
I made a change to the splunk_config.yml to add a new server.  Note:
   * I added the stanza for the server in between some of the existing server stanzas. 

I then ran vagrant reload.   Later I also tried vagrant up --provision <new host>
   * I got errors of various sorts.  

Later I found out that   an existing/used IP by other hosts was assigned  to the new host in ansible_ssh_info.yml, which causes conflict.   

I do notice that a new and correct IP IS re-assigned in hosts file for all hosts.

**Comment by splunkenizer** [comment]
The Vagrant file does calculate the IP address from the starting IP set in the general stanza. The calculation is done everytime the vagrant file runs. If there is a host added in the middle, the sequence is broken and the new host gets the same IP as the machine, which had the same position before.
To add another host after the deployment, either add them at the end or assign static IPs, using 'ip_addr' field on the host level as described in the examples/configuration_description.yml
