### ISSUE TITLE
The machine with the name xxx was not found configured for this Vagrant environment

### ISSUE THREAD

**Issue by kundeng** [thesplunker/Splunkenizer#9]
**Describe the bug**
sometimes, .vagrant/machines/  contains machine confs from another splunk_config.yml or something, and the host-manager plugin generates the following error: 

The machine with the name xxx was not found configured for this Vagrant environment

**To Reproduce**
 - provide splunk_config.yml
 - provide exact commands you executed

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, OSX]
 - Ansible Version [ansible --version]

**Additional context**

**Comment by splunkenizer** [comment]
Hi

You have to destroy the the machines first, before you built new ones. There is also not problem to remove the .vagrant directory manually and delete the machines in the virtualbox gui by hand.
